version: '2'

services:
  web:
    env_file: .env
    ports:
      - '9000:9000'

  cron:
    env_file: .env

  worker:
    env_file: .env

  postgres:
    environment:
      POSTGRES_PASSWORD: ${SENTRY_DB_PASSWORD}
